version: "3.3"

services:
  database:
    container_name: zap_ass_db
    platform: linux/amd64
    image: postgres:12.7
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_USER=admin_zap
    ports:
      - 5432:5432
  redis:
    image: redis
    ports: 
      - 6379:6379


volumes:
  database_data:
